// scripts/hsk1_thai_map_part2.cjs
module.exports = {
  "先生": { th: "คุณผู้ชาย, สามี, มิสเตอร์", pos: "คำนาม", cat: "family_people" },
  "男": { th: "ชาย, เพศชาย", pos: "คำนาม/คุณศัพท์", cat: "family_people" },
  "动": { th: "เคลื่อนไหว, ขยับ", pos: "คำกริยา", cat: "daily_life" },
  "重": { th: "หนัก, สำคัญ", pos: "คำคุณศัพท์", cat: "general" },
  "真的": { th: "จริงๆ, แท้จริง", pos: "คำวิเศษณ์/คุณศัพท์", cat: "emotions" },
  "子": { th: "คำต่อท้ายคำนาม (เช่น 桌子, 孩子)", pos: "คำช่วยต่อท้าย", cat: "general" },
  "远": { th: "ไกล", pos: "คำคุณศัพท์", cat: "travel_transit" },
  "学生": { th: "นักเรียน, นักศึกษา", pos: "คำนาม", cat: "education" },
  "明白": { th: "เข้าใจ, ชัดเจน", pos: "คำกริยา/คุณศัพท์", cat: "education" },
  "记得": { th: "จำได้", pos: "คำกริยา", cat: "education" },
  "歌": { th: "เพลง", pos: "คำนาม", cat: "daily_life" },
  "元": { th: "หยวน (สกุลเงินจีน)", pos: "คำลักษณนาม/นาม", cat: "shopping" },
  "哪里": { th: "ที่ไหน, ที่ใด (หรือ ใช้ถ่อมตน)", pos: "คำสรรพนาม", cat: "travel_transit" },
  "包": { th: "กระเป๋า, ห่อ", pos: "คำนาม/กริยา", cat: "shopping" },
  "楼": { th: "ตึก, อาคาร, ชั้น", pos: "คำนาม", cat: "travel_transit" },
  "那里": { th: "ที่นั่น, ตรงนั้น", pos: "คำสรรพนาม", cat: "travel_transit" },
  "飞": { th: "บิน", pos: "คำกริยา", cat: "travel_transit" },
  "介绍": { th: "แนะนำ (ให้รู้จัก/ให้ข้อมูล)", pos: "คำกริยา", cat: "greetings" },
  "下午": { th: "ช่วงบ่าย", pos: "คำนาม", cat: "numbers_time" },
  "出去": { th: "ออกไปข้างนอก", pos: "คำกริยาบอกทิศทาง", cat: "daily_life" },
  "唱": { th: "ร้อง (เพลง)", pos: "คำกริยา", cat: "daily_life" },
  "大学": { th: "มหาวิทยาลัย", pos: "คำนาม", cat: "education" },
  "病": { th: "ป่วย, โรค", pos: "คำนาม/กริยา", cat: "daily_life" },
  "她们": { th: "พวกเธอ (ผู้หญิงล้วน)", pos: "คำสรรพนาม", cat: "family_people" },
  "今年": { th: "ปีนี้", pos: "คำนาม", cat: "numbers_time" },
  "听到": { th: "ได้ยิน", pos: "คำกริยา", cat: "daily_life" },
  "女儿": { th: "ลูกสาว", pos: "คำนาม", cat: "family_people" },
  "说话": { th: "พูดคุย, คุยกัน", pos: "คำกริยา", cat: "daily_life" },
  "汽车": { th: "รถยนต์", pos: "คำนาม", cat: "travel_transit" },
  "去年": { th: "ปีที่แล้ว", pos: "คำนาม", cat: "numbers_time" },
  "试": { th: "ลอง, ทดลอง", pos: "คำกริยา", cat: "daily_life" },
  "来到": { th: "มาถึง, เดินทางมาถึง", pos: "คำกริยา", cat: "travel_transit" },
  "票": { th: "ตั๋ว, บัตร", pos: "คำนาม", cat: "travel_transit" },
  "西": { th: "ทิศตะวันตก", pos: "คำนาม", cat: "travel_transit" },
  "床": { th: "เตียง, เตียงนอน", pos: "คำนาม", cat: "daily_life" },
  "第": { th: "ลำดับที่... (นำหน้าตัวเลข)", pos: "คำนำหน้า", cat: "numbers_time" },
  "回到": { th: "กลับไปถึง, กลับสู่", pos: "คำกริยา", cat: "travel_transit" },
  "差": { th: "แย่, ขาดอีก (เวลา/จำนวน)", pos: "คำคุณศัพท์/กริยา", cat: "numbers_time" },
  "家里": { th: "ที่บ้าน, ในบ้าน", pos: "คำนาม", cat: "family_people" },
  "教": { th: "สอน", pos: "คำกริยา", cat: "education" },
  "不用": { th: "ไม่ต้อง, ไม่จำเป็น", pos: "คำช่วย/วิเศษณ์", cat: "daily_life" },
  "忘": { th: "ลืม", pos: "คำกริยา", cat: "daily_life" },
  "认真": { th: "ตั้งใจ, จริงจัง", pos: "คำคุณศัพท์", cat: "education" },
  "电": { th: "ไฟฟ้า", pos: "คำนาม", cat: "daily_life" },
  "房子": { th: "บ้าน, ห้องพัก", pos: "คำนาม", cat: "daily_life" },
  "山": { th: "ภูเขา", pos: "คำนาม", cat: "nature_weather" },
  "常": { th: "บ่อย, เสมอ", pos: "คำวิเศษณ์", cat: "numbers_time" },
  "回答": { th: "ตอบ, คำตอบ", pos: "คำกริยา/คำนาม", cat: "education" },
  "记": { th: "จดจำ, บันทึก", pos: "คำกริยา", cat: "education" },
  "关": { th: "ปิด", pos: "คำกริยา", cat: "daily_life" },
  "回去": { th: "กลับไป", pos: "คำกริยาบอกทิศทาง", cat: "daily_life" },
  "累": { th: "เหนื่อย", pos: "คำคุณศัพท์", cat: "emotions" },
  "病人": { th: "คนไข้, ผู้ป่วย", pos: "คำนาม", cat: "family_people" },
  "肉": { th: "เนื้อสัตว์", pos: "คำนาม", cat: "food_drinks" },
  "班": { th: "ชั้นเรียน, กะทำงาน, รอบ", pos: "คำนาม", cat: "education" },
  "坏": { th: "เสีย, พัง, เลวร้าย", pos: "คำคุณศัพท์", cat: "daily_life" },
  "一边": { th: "ด้านหนึ่ง, พลาง...พลาง...", pos: "คำวิเศษณ์/นาม", cat: "daily_life" },
  "洗": { th: "ล้าง, ซัก, สระ", pos: "คำกริยา", cat: "daily_life" },
  "有的": { th: "บางส่วน, บางคน", pos: "คำสรรพนาม", cat: "general" },
  "毛": { th: "ขน, เหมา (สิบสตางค์จีน)", pos: "คำนาม/ลักษณนาม", cat: "shopping" },
  "忘记": { th: "ลืม, หลงลืม", pos: "คำกริยา", cat: "daily_life" },
  "吃饭": { th: "กินข้าว, รับประทานอาหาร", pos: "คำกริยา", cat: "food_drinks" },
  "动作": { th: "การกระทำ, ท่าทาง", pos: "คำนาม", cat: "daily_life" },
  "饿": { th: "หิว", pos: "คำคุณศัพท์", cat: "food_drinks" },
  "树": { th: "ต้นไม้", pos: "คำนาม", cat: "nature_weather" },
  "生日": { th: "วันเกิด", pos: "คำนาม", cat: "numbers_time" },
  "东": { th: "ทิศตะวันออก", pos: "คำนาม", cat: "travel_transit" },
  "课": { th: "บทเรียน, วิชา", pos: "คำนาม", cat: "education" },
  "一半": { th: "ครึ่งหนึ่ง", pos: "คำบอกจำนวน", cat: "numbers_time" },
  "家人": { th: "คนในครอบครัว", pos: "คำนาม", cat: "family_people" },
  "有时": { th: "บางครั้ง, เป็นบางเวลา", pos: "คำวิเศษณ์", cat: "numbers_time" },
  "小姐": { th: "คุณผู้หญิง, นางสาว", pos: "คำนาม", cat: "family_people" },
  "进去": { th: "เข้าไปข้างใน", pos: "คำกริยาบอกทิศทาง", cat: "daily_life" },
  "没什么": { th: "ไม่มีอะไร, ไม่เป็นไร", pos: "วลี", cat: "greetings" },
  "路上": { th: "บนถนน, ระหว่างทาง", pos: "คำนาม", cat: "travel_transit" },
  "最好": { th: "ดีที่สุด, ทางที่ดีควร...", pos: "คำคุณศัพท์/วิเศษณ์", cat: "general" },
  "南": { th: "ทิศใต้", pos: "คำนาม", cat: "travel_transit" },
  "考试": { th: "สอบ, การสอบ", pos: "คำกริยา/คำนาม", cat: "education" },
  "有时候": { th: "บางครั้งบางคราว", pos: "คำวิเศษณ์", cat: "numbers_time" },
  "旁边": { th: "ด้านข้าง, ข้างๆ", pos: "คำนามบอกทิศทาง", cat: "travel_transit" },
  "北": { th: "ทิศเหนือ", pos: "คำนาม", cat: "travel_transit" },
  "帮忙": { th: "ช่วยเหลือ", pos: "คำกริยา", cat: "daily_life" },
  "进来": { th: "เข้ามาข้างใน", pos: "คำกริยาบอกทิศทาง", cat: "daily_life" },
  "见面": { th: "พบกัน, เจอหน้า", pos: "คำกริยา", cat: "daily_life" },
  "好看": { th: "ดูดี, สวย, น่าดู", pos: "คำคุณศัพท์", cat: "emotions" },
  "中间": { th: "ตรงกลาง, ท่ามกลาง", pos: "คำนามบอกทิศทาง", cat: "travel_transit" },
  "女生": { th: "เด็กผู้หญิง, นักเรียนหญิง", pos: "คำนาม", cat: "family_people" },
  "地点": { th: "สถานที่, จุดนัดพบ", pos: "คำนาม", cat: "travel_transit" },
  "雨": { th: "ฝน", pos: "คำนาม", cat: "nature_weather" },
  "车上": { th: "บนรถ", pos: "คำนาม", cat: "travel_transit" },
  "考": { th: "สอบ, ทดสอบ", pos: "คำกริยา", cat: "education" },
  "生气": { th: "โกรธ, โมโห", pos: "คำกริยา/คุณศัพท์", cat: "emotions" },
  "地上": { th: "บนพื้น", pos: "คำนาม", cat: "daily_life" },
  "上午": { th: "ช่วงเช้าสาย", pos: "คำนาม", cat: "numbers_time" },
  "一会儿": { th: "ครู่หนึ่ง, สักพัก", pos: "คำนาม/วิเศษณ์", cat: "numbers_time" },
  "记住": { th: "จำไว้, จำให้ได้", pos: "คำกริยา", cat: "education" },
  "下次": { th: "ครั้งหน้า, คราวหน้า", pos: "คำนาม", cat: "numbers_time" },
  "知识": { th: "ความรู้", pos: "คำนาม", cat: "education" },
  "学院": { th: "วิทยาลัย, คณะวิชา", pos: "คำนาม", cat: "education" },
  "老人": { th: "คนชรา, ผู้สูงอายุ", pos: "คำนาม", cat: "family_people" }
};
