// scripts/hsk1_thai_map_part3.cjs
module.exports = {
  "页": { th: "หน้า (หนังสือ)", pos: "คำลักษณนาม", cat: "education" },
  "工人": { th: "คนงาน, กรรมกร", pos: "คำนาม", cat: "work_business" },
  "那边": { th: "ด้านโน้น, ทางนั้น", pos: "คำนามบอกทิศทาง", cat: "travel_transit" },
  "干净": { th: "สะอาด", pos: "คำคุณศัพท์", cat: "daily_life" },
  "在家": { th: "อยู่ที่บ้าน", pos: "วลี/กริยา", cat: "daily_life" },
  "网上": { th: "บนอินเทอร์เน็ต, ออนไลน์", pos: "คำนาม", cat: "daily_life" },
  "明年": { th: "ปีหน้า", pos: "คำนาม", cat: "numbers_time" },
  "妹": { th: "น้องสาว", pos: "คำนาม", cat: "family_people" },
  "不对": { th: "ไม่ถูกต้อง, ผิด", pos: "คำคุณศัพท์", cat: "education" },
  "是不是": { th: "ใช่หรือไม่, หรือเปล่า", pos: "วลี", cat: "greetings" },
  "开车": { th: "ขับรถ", pos: "คำกริยา", cat: "travel_transit" },
  "干什么": { th: "ทำอะไร", pos: "วลีคำถาม", cat: "daily_life" },
  "奶": { th: "นม, ย่า/ยาย", pos: "คำนาม", cat: "food_drinks" },
  "门口": { th: "หน้าประตู, ทางเข้า", pos: "คำนามบอกทิศทาง", cat: "travel_transit" },
  "这边": { th: "ด้านนี้, ทางนี้", pos: "คำนามบอกทิศทาง", cat: "travel_transit" },
  "男生": { th: "เด็กผู้ชาย, นักเรียนชาย", pos: "คำนาม", cat: "family_people" },
  "火车": { th: "รถไฟ", pos: "คำนาม", cat: "travel_transit" },
  "奶奶": { th: "ย่า", pos: "คำนาม", cat: "family_people" },
  "上次": { th: "ครั้งก่อน, คราวที่แล้ว", pos: "คำนาม", cat: "numbers_time" },
  "右边": { th: "ด้านขวา", pos: "คำนามบอกทิศทาง", cat: "travel_transit" },
  "上学": { th: "ไปโรงเรียน, เข้าเรียน", pos: "คำกริยา", cat: "education" },
  "牛奶": { th: "นมวัว", pos: "คำนาม", cat: "food_drinks" },
  "女朋友": { th: "แฟนสาว, เพื่อนผู้หญิง", pos: "คำนาม", cat: "family_people" },
  "上课": { th: "เข้าเรียน, เริ่มคาบเรียน", pos: "คำกริยา", cat: "education" },
  "爷爷": { th: "ปู่", pos: "คำนาม", cat: "family_people" },
  "听见": { th: "ได้ยิน", pos: "คำกริยา", cat: "daily_life" },
  "新年": { th: "ปีใหม่", pos: "คำนาม", cat: "numbers_time" },
  "男朋友": { th: "แฟนหนุ่ม, เพื่อนผู้ชาย", pos: "คำนาม", cat: "family_people" },
  "水果": { th: "ผลไม้", pos: "คำนาม", cat: "food_drinks" },
  "读书": { th: "อ่านหนังสือ, เรียนหนังสือ", pos: "คำกริยา", cat: "education" },
  "商店": { th: "ร้านค้า", pos: "คำนาม", cat: "shopping" },
  "鸡蛋": { th: "ไข่ไก่", pos: "คำนาม", cat: "food_drinks" },
  "没关系": { th: "ไม่เป็นไร", pos: "วลีสุภาพ", cat: "greetings" },
  "地图": { th: "แผนที่", pos: "คำนาม", cat: "travel_transit" },
  "姐": { th: "พี่สาว", pos: "คำนาม", cat: "family_people" },
  "坐下": { th: "นั่งลง", pos: "คำกริยา", cat: "daily_life" },
  "桌子": { th: "โต๊ะ", pos: "คำนาม", cat: "daily_life" },
  "白天": { th: "กลางวัน", pos: "คำนาม", cat: "numbers_time" },
  "哪些": { th: "อันไหนบ้าง, พวกไหนบ้าง", pos: "คำสรรพนาม", cat: "general" },
  "晚饭": { th: "อาหารเย็น, มื้อค่ำ", pos: "คำนาม", cat: "food_drinks" },
  "小学": { th: "โรงเรียนประถม", pos: "คำนาม", cat: "education" },
  "图书馆": { th: "ห้องสมุด", pos: "คำนาม", cat: "education" },
  "开玩笑": { th: "ล้อเล่น, พูดเล่น", pos: "คำกริยา", cat: "daily_life" },
  "国外": { th: "ต่างประเทศ", pos: "คำนาม", cat: "travel_transit" },
  "日期": { th: "วันที่", pos: "คำนาม", cat: "numbers_time" },
  "饭店": { th: "ร้านอาหาร, โรงแรม", pos: "คำนาม", cat: "food_drinks" },
  "中学": { th: "โรงเรียนมัธยม", pos: "คำนาม", cat: "education" },
  "上网": { th: "เล่นเน็ต, ใช้งานอินเทอร์เน็ต", pos: "คำกริยา", cat: "daily_life" },
  "面包": { th: "ขนมปัง", pos: "คำนาม", cat: "food_drinks" },
  "外国": { th: "ต่างประเทศ, เมืองนอก", pos: "คำนาม", cat: "travel_transit" },
  "生病": { th: "ป่วย, ไม่สบาย", pos: "คำกริยา", cat: "daily_life" },
  "好听": { th: "เพราะ, น่าฟัง", pos: "คำคุณศัพท์", cat: "daily_life" },
  "钱包": { th: "กระเป๋าสตางค์", pos: "คำนาม", cat: "shopping" },
  "大学生": { th: "นักศึกษา", pos: "คำนาม", cat: "education" },
  "走路": { th: "เดิน, เดินทางด้วยเท้า", pos: "คำกริยา", cat: "travel_transit" },
  "小朋友": { th: "เด็กๆ, หนูน้อย", pos: "คำนาม", cat: "family_people" },
  "左边": { th: "ด้านซ้าย", pos: "คำนามบอกทิศทาง", cat: "travel_transit" },
  "有用": { th: "มีประโยชน์", pos: "คำคุณศัพท์", cat: "education" },
  "爱好": { th: "งานอดิเรก, ความชอบ", pos: "คำนาม/กริยา", cat: "daily_life" },
  "不大": { th: "ไม่ค่อยใหญ่, เล็กน้อย", pos: "คำคุณศัพท์", cat: "daily_life" },
  "午饭": { th: "อาหารกลางวัน", pos: "คำนาม", cat: "food_drinks" },
  "上车": { th: "ขึ้นรถ", pos: "คำกริยา", cat: "travel_transit" },
  "马路": { th: "ถนน", pos: "คำนาม", cat: "travel_transit" },
  "机票": { th: "ตั๋วเครื่องบิน", pos: "คำนาม", cat: "travel_transit" },
  "楼上": { th: "ชั้นบน", pos: "คำนามบอกทิศทาง", cat: "travel_transit" },
  "打球": { th: "เล่นบอล, เล่นกีฬาประเภทบอล", pos: "คำกริยา", cat: "daily_life" },
  "下车": { th: "ลงรถ", pos: "คำกริยา", cat: "travel_transit" },
  "放假": { th: "ปิดเทอม, หยุดพักผ่อน", pos: "คำกริยา", cat: "daily_life" },
  "路口": { th: "ทางแยก, ปากทาง", pos: "คำนามบอกทิศทาง", cat: "travel_transit" },
  "有名": { th: "มีชื่อเสียง, โด่งดัง", pos: "คำคุณศัพท์", cat: "general" },
  "中文": { th: "ภาษาจีน", pos: "คำนาม", cat: "education" },
  "弟": { th: "น้องชาย", pos: "คำนาม", cat: "family_people" },
  "电视机": { th: "เครื่องรับโทรทัศน์, ทีวี", pos: "คำนาม", cat: "daily_life" },
  "早饭": { th: "อาหารเช้า", pos: "คำนาม", cat: "food_drinks" },
  "书店": { th: "ร้านหนังสือ", pos: "คำนาม", cat: "shopping" },
  "放学": { th: "เลิกเรียน", pos: "คำกริยา", cat: "education" },
  "关上": { th: "ปิดสนิท, ปิด (ประตู/หน้าต่าง)", pos: "คำกริยา", cat: "daily_life" },
  "玩儿": { th: "เล่น, เที่ยวเล่น", pos: "คำกริยา", cat: "daily_life" },
  "半天": { th: "ครึ่งวัน, เวลานานมาก", pos: "คำนาม", cat: "numbers_time" },
  "星期天": { th: "วันอาทิตย์", pos: "คำนาม", cat: "numbers_time" },
  "车票": { th: "ตั๋วรถ", pos: "คำนาม", cat: "travel_transit" },
  "看病": { th: "หาหมอ, ตรวจโรค", pos: "คำกริยา", cat: "daily_life" },
  "前天": { th: "เมื่อวานซืน", pos: "คำนาม", cat: "numbers_time" },
  "后天": { th: "วันมะรืน", pos: "คำนาม", cat: "numbers_time" },
  "渴": { th: "กระหายน้ำ, คอแห้ง", pos: "คำคุณศัพท์", cat: "food_drinks" },
  "下课": { th: "เลิกเรียน, หมดคาบเรียน", pos: "คำกริยา", cat: "education" },
  "里边": { th: "ข้างใน, ด้านใน", pos: "คำนามบอกทิศทาง", cat: "travel_transit" },
  "外语": { th: "ภาษาต่างประเทศ", pos: "คำนาม", cat: "education" },
  "没事儿": { th: "ไม่เป็นไร, ไม่มีปัญหา", pos: "วลีสุภาพ", cat: "greetings" },
  "一块儿": { th: "ด้วยกัน, ร่วมกัน", pos: "คำวิเศษณ์", cat: "daily_life" },
  "书包": { th: "กระเป๋านักเรียน", pos: "คำนาม", cat: "education" },
  "小学生": { th: "นักเรียนประถม", pos: "คำนาม", cat: "education" },
  "外边": { th: "ข้างนอก, ด้านนอก", pos: "คำนามบอกทิศทาง", cat: "travel_transit" },
  "中学生": { th: "นักเรียนมัธยม", pos: "คำนาม", cat: "education" },
  "本子": { th: "สมุด", pos: "คำนาม", cat: "education" },
  "星期日": { th: "วันอาทิตย์", pos: "คำนาม", cat: "numbers_time" },
  "课本": { th: "หนังสือเรียน, ตำราเรียน", pos: "คำนาม", cat: "education" },
  "后边": { th: "ข้างหลัง, ด้านหลัง", pos: "คำนามบอกทิศทาง", cat: "travel_transit" },
  "西边": { th: "ทางทิศตะวันตก", pos: "คำนามบอกทิศทาง", cat: "travel_transit" },
  "上边": { th: "ข้างบน, ด้านบน", pos: "คำนามบอกทิศทาง", cat: "travel_transit" },
  "打车": { th: "เรียกแท็กซี่, นั่งรถแท็กซี่", pos: "คำกริยา", cat: "travel_transit" },
  "东边": { th: "ทางทิศตะวันออก", pos: "คำนามบอกทิศทาง", cat: "travel_transit" },
  "南边": { th: "ทางทิศใต้", pos: "คำนามบอกทิศทาง", cat: "travel_transit" },
  "北边": { th: "ทางทิศเหนือ", pos: "คำนามบอกทิศทาง", cat: "travel_transit" },
  "女孩儿": { th: "เด็กผู้หญิง", pos: "คำนาม", cat: "family_people" },
  "下边": { th: "ข้างล่าง, ด้านล่าง", pos: "คำนามบอกทิศทาง", cat: "travel_transit" },
  "汉字": { th: "อักษรจีน", pos: "คำนาม", cat: "education" },
  "请进": { th: "เชิญเข้าข้างใน", pos: "วลีสุภาพ", cat: "greetings" },
  "好玩儿": { th: "สนุก, น่าสนุก", pos: "คำคุณศัพท์", cat: "daily_life" },
  "前边": { th: "ข้างหน้า, ด้านหน้า", pos: "คำนามบอกทิศทาง", cat: "travel_transit" },
  "小孩儿": { th: "เด็กน้อย, เด็กเล็ก", pos: "คำนาม", cat: "family_people" },
  "教学楼": { th: "อาคารเรียน", pos: "คำนาม", cat: "education" },
  "网友": { th: "เพื่อนทางเน็ต", pos: "คำนาม", cat: "family_people" },
  "课文": { th: "บทอ่าน, บทเรียน", pos: "คำนาม", cat: "education" },
  "请坐": { th: "เชิญนั่ง", pos: "วลีสุภาพ", cat: "greetings" },
  "半年": { th: "ครึ่งปี", pos: "คำนาม", cat: "numbers_time" },
  "听写": { th: "เขียนตามคำบอก", pos: "คำกริยา/นาม", cat: "education" },
  "面条儿": { th: "ก๋วยเตี๋ยว, บะหมี่", pos: "คำนาม", cat: "food_drinks" },
  "男孩儿": { th: "เด็กผู้ชาย", pos: "คำนาม", cat: "family_people" },
  "一下儿": { th: "สักครู่, แวบหนึ่ง, ประเดี๋ยว", pos: "คำบอกจำนวน/วิเศษณ์", cat: "numbers_time" },
  "有一些": { th: "มีบ้าง, มีจำนวนหนึ่ง", pos: "คำสรรพนาม/วลี", cat: "general" }
};
