// scripts/hsk1_thai_map_part1.cjs
module.exports = {
  "就": { th: "ก็, ทันทีที่, เพียงแค่", pos: "คำวิเศษณ์", cat: "general" },
  "说": { th: "พูด, บอก", pos: "คำกริยา", cat: "daily_life" },
  "我们": { th: "พวกเรา", pos: "คำสรรพนาม", cat: "family_people" },
  "都": { th: "ล้วน, ทั้งหมด, ก็", pos: "คำวิเศษณ์", cat: "general" },
  "上": { th: "บน, ขึ้น, ก่อนหน้า", pos: "คำบุพบท/กริยา", cat: "daily_life" },
  "还": { th: "ยัง, ยังคง, นอกจากนี้ยัง", pos: "คำวิเศษณ์", cat: "general" },
  "她": { th: "เธอ, เขา (ผู้หญิง)", pos: "คำสรรพนาม", cat: "family_people" },
  "着": { th: "อยู่ (กำลังกระทำ/คงสภาพ)", pos: "คำช่วย", cat: "general" },
  "能": { th: "สามารถ, ได้", pos: "คำกริยานุเคราะห์", cat: "general" },
  "他们": { th: "พวกเขา", pos: "คำสรรพนาม", cat: "family_people" },
  "做": { th: "ทำ, ปรุง, ประกอบ", pos: "คำกริยา", cat: "daily_life" },
  "过": { th: "เคย, ผ่าน", pos: "คำช่วย/กริยา", cat: "general" },
  "没": { th: "ไม่, ไม่มี, ยังไม่ได้", pos: "คำวิเศษณ์", cat: "general" },
  "从": { th: "จาก, ตั้งแต่", pos: "คำบุพบท", cat: "travel_transit" },
  "下": { th: "ล่าง, ลง, ถัดไป", pos: "คำบุพบท/กริยา", cat: "daily_life" },
  "里": { th: "ใน, ด้านใน", pos: "คำนามบอกทิศทาง", cat: "daily_life" },
  "真": { th: "จริง, จริงๆ", pos: "คำวิเศษณ์", cat: "emotions" },
  "年": { th: "ปี", pos: "คำนาม/ลักษณนาม", cat: "numbers_time" },
  "用": { th: "ใช้", pos: "คำกริยา", cat: "daily_life" },
  "等": { th: "รอ, และอื่นๆ", pos: "คำกริยา/คำช่วย", cat: "daily_life" },
  "再": { th: "อีกครั้ง, ค่อย", pos: "คำวิเศษณ์", cat: "numbers_time" },
  "呢": { th: "ล่ะ, นะ, กำลัง...อยู่", pos: "คำช่วยน้ำเสียง", cat: "greetings" },
  "次": { th: "ครั้ง, หน", pos: "คำลักษณนาม", cat: "numbers_time" },
  "知道": { th: "รู้, ทราบ", pos: "คำกริยา", cat: "daily_life" },
  "时候": { th: "ตอน, เวลา, ขณะที่", pos: "คำนาม", cat: "numbers_time" },
  "事": { th: "เรื่อง, ธุระ, สิ่ง", pos: "คำนาม", cat: "daily_life" },
  "后": { th: "หลัง, ด้านหลัง, หลังจาก", pos: "คำนามบอกทิศทาง", cat: "numbers_time" },
  "你们": { th: "พวกคุณ, พวกเธอ", pos: "คำสรรพนาม", cat: "family_people" },
  "时间": { th: "เวลา", pos: "คำนาม", cat: "numbers_time" },
  "地": { th: "อย่าง (คำช่วยเชื่อมคำวิเศษณ์)", pos: "คำช่วย", cat: "general" },
  "这些": { th: "เหล่านี้, พวกนี้", pos: "คำสรรพนาม", cat: "general" },
  "跟": { th: "กับ, ตาม", pos: "คำบุพบท/กริยา", cat: "daily_life" },
  "新": { th: "ใหม่", pos: "คำคุณศัพท์", cat: "daily_life" },
  "找": { th: "หา, ทอนเงิน", pos: "คำกริยา", cat: "daily_life" },
  "打": { th: "ตี, เล่น, โทร", pos: "คำกริยา", cat: "daily_life" },
  "还有": { th: "และยังมี, ยังมี", pos: "คำสันธาน", cat: "general" },
  "话": { th: "คำพูด, ภาษา", pos: "คำนาม", cat: "daily_life" },
  "还是": { th: "หรือว่า, ยังคง", pos: "คำสันธาน/วิเศษณ์", cat: "general" },
  "觉得": { th: "รู้สึกว่า, คิดว่า", pos: "คำกริยา", cat: "emotions" },
  "看到": { th: "มองเห็น, เห็น", pos: "คำกริยา", cat: "daily_life" },
  "起来": { th: "ลุกขึ้น, ขึ้นมา", pos: "คำกริยาบอกทิศทาง", cat: "daily_life" },
  "起": { th: "ลุกขึ้น, เริ่มต้น", pos: "คำกริยา", cat: "daily_life" },
  "车": { th: "รถ, ยานพาหนะ", pos: "คำนาม", cat: "travel_transit" },
  "一些": { th: "จำนวนหนึ่ง, บ้าง, นิดหน่อย", pos: "คำบอกจำนวน", cat: "numbers_time" },
  "找到": { th: "หาเจอ, พบ", pos: "คำกริยา", cat: "daily_life" },
  "孩子": { th: "เด็ก, ลูก", pos: "คำนาม", cat: "family_people" },
  "这里": { th: "ที่นี่, ตรงนี้", pos: "คำสรรพนาม", cat: "travel_transit" },
  "请": { th: "กรุณา, เชิญ, เลี้ยง", pos: "คำกริยา", cat: "greetings" },
  "一样": { th: "เหมือนกัน, เช่นเดียวกัน", pos: "คำคุณศัพท์", cat: "general" },
  "重要": { th: "สำคัญ", pos: "คำคุณศัพท์", cat: "education" },
  "告诉": { th: "บอก, แจ้งให้ทราบ", pos: "คำกริยา", cat: "daily_life" },
  "出来": { th: "ออกมา", pos: "คำกริยาบอกทิศทาง", cat: "daily_life" },
  "地方": { th: "สถานที่, ที่", pos: "คำนาม", cat: "travel_transit" },
  "最后": { th: "สุดท้าย, ท้ายที่สุด", pos: "คำนาม/คำวิเศษณ์", cat: "numbers_time" },
  "老": { th: "แก่, เก่า, มักจะ", pos: "คำคุณศัพท์/วิเศษณ์", cat: "family_people" },
  "岁": { th: "ขวบ, ปี (อายุ)", pos: "คำลักษณนาม", cat: "numbers_time" },
  "行": { th: "ได้, โอเค", pos: "คำกริยา/คุณศัพท์", cat: "daily_life" },
  "放": { th: "วาง, ปล่อย, ใส่", pos: "คำกริยา", cat: "daily_life" },
  "住": { th: "พักอาศัย, อยู่", pos: "คำกริยา", cat: "daily_life" },
  "拿": { th: "ถือ, หยิบ, เอา", pos: "คำกริยา", cat: "daily_life" },
  "正": { th: "กำลัง...อยู่, ตรง", pos: "คำวิเศษณ์", cat: "numbers_time" },
  "先": { th: "ก่อน, อันดับแรก", pos: "คำวิเศษณ์", cat: "numbers_time" },
  "得到": { th: "ได้รับ, ได้มา", pos: "คำกริยา", cat: "daily_life" },
  "那些": { th: "เหล่านั้น, พวกนั้น", pos: "คำสรรพนาม", cat: "general" },
  "准备": { th: "เตรียมตัว, เตรียมพร้อม", pos: "คำกริยา", cat: "daily_life" },
  "进": { th: "เข้า, ก้าวหน้า", pos: "คำกริยา", cat: "daily_life" },
  "写": { th: "เขียน", pos: "คำกริยา", cat: "education" },
  "国家": { th: "ประเทศ", pos: "คำนาม", cat: "travel_transit" },
  "电话": { th: "โทรศัพท์", pos: "คำนาม", cat: "daily_life" },
  "女": { th: "หญิง, เพศหญิง", pos: "คำนาม/คุณศัพท์", cat: "family_people" },
  "送": { th: "ส่ง, มอบให้", pos: "คำกริยา", cat: "daily_life" },
  "笑": { th: "หัวเราะ, ยิ้ม", pos: "คำกริยา", cat: "emotions" },
  "女人": { th: "ผู้หญิง", pos: "คำนาม", cat: "family_people" },
  "小时": { th: "ชั่วโมง", pos: "คำนาม", cat: "numbers_time" },
  "有些": { th: "บางส่วน, บ้าง, ค่อนข้าง", pos: "คำสรรพนาม/วิเศษณ์", cat: "general" },
  "日": { th: "วัน, พระอาทิตย์", pos: "คำนาม/ลักษณนาม", cat: "numbers_time" },
  "别人": { th: "คนอื่น", pos: "คำสรรพนาม", cat: "family_people" },
  "站": { th: "ยืน, สถานี", pos: "คำกริยา/คำนาม", cat: "travel_transit" },
  "路": { th: "ถนน, ทาง, สาย", pos: "คำนาม", cat: "travel_transit" },
  "男人": { th: "ผู้ชาย", pos: "คำนาม", cat: "family_people" },
  "正在": { th: "กำลัง...อยู่", pos: "คำวิเศษณ์", cat: "numbers_time" },
  "学校": { th: "โรงเรียน", pos: "คำนาม", cat: "education" },
  "花": { th: "ดอกไม้, ใช้จ่าย", pos: "คำนาม/กริยา", cat: "nature_weather" },
  "早": { th: "เช้า, เร็ว, ก่อนเวลา", pos: "คำคุณศัพท์/คำทักทาย", cat: "numbers_time" },
  "们": { th: "พวก (คำต่อท้ายพหูพจน์)", pos: "คำช่วยต่อท้าย", cat: "family_people" },
  "身上": { th: "บนตัว, ในตัว", pos: "คำนาม", cat: "daily_life" },
  "干": { th: "ทำ (งาน)", pos: "คำกริยา", cat: "work_business" },
  "睡": { th: "นอน, นอนหลับ", pos: "คำกริยา", cat: "daily_life" },
  "回来": { th: "กลับมา", pos: "คำกริยาบอกทิศทาง", cat: "daily_life" },
  "外": { th: "นอก, ด้านนอก", pos: "คำนามบอกทิศทาง", cat: "travel_transit" },
  "球": { th: "ลูกบอล, ลูกบอลกลม", pos: "คำนาม", cat: "daily_life" },
  "学": { th: "เรียน, ศึกษา", pos: "คำกริยา", cat: "education" },
  "第二": { th: "ที่สอง, ลำดับสอง", pos: "คำบอกลำดับ", cat: "numbers_time" },
  "错": { th: "ผิด, ผิดพลาด", pos: "คำคุณศัพท์", cat: "education" },
  "少": { th: "น้อย, ขาด", pos: "คำคุณศัพท์", cat: "numbers_time" },
  "别的": { th: "อย่างอื่น, อื่นๆ", pos: "คำสรรพนาม", cat: "general" },
  "难": { th: "ยาก, ลำบาก", pos: "คำคุณศัพท์", cat: "education" },
  "间": { th: "ห้อง (ลักษณนาม), ระหว่าง", pos: "คำลักษณนาม/นาม", cat: "daily_life" },
  "回家": { th: "กลับบ้าน", pos: "คำกริยา", cat: "daily_life" },
  "晚": { th: "ค่ำ, ดึก, สาย", pos: "คำคุณศัพท์/นาม", cat: "numbers_time" }
};
